version: 2

sphinx:
  configuration: doc/conf.py

formats: []

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dnssec
        - idna
        - doh

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
