# Copyright (C) Dnspython Contributors, see LICENSE for text of ISC license

from typing import ClassVar, Final, Tuple

from dns.enum import IntEnum
from dns.exception import DNSException

class Rcode(IntEnum):
    NOERROR: Final[ClassVar[int]] = ...
    FORMERR: Final[ClassVar[int]] = ...
    SERVFAIL: Final[ClassVar[int]] = ...
    NXDOMAIN: Final[ClassVar[int]] = ...
    NOTIMP: Final[ClassVar[int]] = ...
    REFUSED: Final[ClassVar[int]] = ...
    YXDOMAIN: Final[ClassVar[int]] = ...
    YXRRSET: Final[ClassVar[int]] = ...
    NXRRSET: Final[ClassVar[int]] = ...
    NOTAUTH: Final[ClassVar[int]] = ...
    NOTZONE: Final[ClassVar[int]] = ...
    DSOTYPENI: Final[ClassVar[int]] = ...
    BADVERS: Final[ClassVar[int]] = ...
    BADSIG: Final[ClassVar[int]] = ...
    BADKEY: Final[ClassVar[int]] = ...
    BADTIME: Final[ClassVar[int]] = ...
    BADMODE: Final[ClassVar[int]] = ...
    BADNAME: Final[ClassVar[int]] = ...
    BADALG: Final[ClassVar[int]] = ...
    BADTRUNC: Final[ClassVar[int]] = ...
    BADCOOKIE: Final[ClassVar[int]] = ...

    @classmethod
    def _maximum(cls) -> int: ...

    @classmethod
    def _unknown_exception_class(cls) -> type:
        return UnknownRcode

class UnknownRcode(DNSException): ...

def from_text(text: str) -> int: ...

def from_flags(flags: int, ednsflags: int) -> int: ...

def to_flags(value: int) -> Tuple[int, int]: ...

def to_text(value: int, tsig: bool = False) -> str: ...

NOERROR: Final[int] = ...
FORMERR: Final[int] = ...
SERVFAIL: Final[int] = ...
NXDOMAIN: Final[int] = ...
NOTIMP: Final[int] = ...
REFUSED: Final[int] = ...
YXDOMAIN: Final[int] = ...
YXRRSET: Final[int] = ...
NXRRSET: Final[int] = ...
NOTAUTH: Final[int] = ...
NOTZONE: Final[int] = ...
DSOTYPENI: Final[int] = ...
BADVERS: Final[int] = ...
BADSIG: Final[int] = ...
BADKEY: Final[int] = ...
BADTIME: Final[int] = ...
BADMODE: Final[int] = ...
BADNAME: Final[int] = ...
BADALG: Final[int] = ...
BADTRUNC: Final[int] = ...
BADCOOKIE: Final[int] = ...
