# Copyright (C) Dnspython Contributors, see LICENSE for text of ISC license

from typing import Any, Final

from dns.exception import DNSException

RESERVED0: Final[int] = ...
IN: Final[int] = ...
CH: Final[int] = ...
HS: Final[int] = ...
NONE: Final[int] = ...
ANY: Final[int] = ...

class UnknownRdataclass(DNSException): ...

def from_text(text: Any) -> int: ...
def to_text(value: Any) -> str: ...
def is_metaclass(rdclass: Any) -> bool: ...
